### ISSUE TITLE
Color variables should not be CFPB-specific

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-tables#11]
The color variables should use non-CFPB-specific colors, and we need to add overrides for those variables to our [cf-theme-overrides.less](https://github.com/cfpb/generator-cf/blob/master/app/templates/src/static/css/cf-theme-overrides.less) file to set them to our CFPB -specific values.

**Comment by KimberlyMunoz** [comment]
@mistergone: Is this issue resolved?

**Comment by mistergone** [comment]
It's in PR #12, so this issue can be closed once that PR is merged.

**Comment by mistergone** [comment]
Merged in PR #12!
