### ISSUE TITLE
Remove unnecessary nesting for .table_cell__right-align

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-tables#4]
I don't think there's any reason to nest `.table_cell__right-align` within `table`, is there?

https://github.com/cfpb/front-end/blob/54ca2885503632c198c5f964bcf09f8272a08260/css.md#avoid-creating-elements-of-modifiers

**Comment by mistergone** [comment]
No, probably not. :smile:

**Comment by mistergone** [comment]
Merged in PR #12!
