### ISSUE TITLE
Change striping setup to avoid overriding

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-tables#7]
If you were to put the [basic striping styles](https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L395-L400) in a `min-width` query, you could [remove them from the `max-width` query](https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L395-L400) and avoid the override.

**Comment by mistergone** [comment]
I have a slight problem where the "Comparative with Horizontal Scroll" variation should remain striped at all widths. It seems to me, one way or another, I'm going to have to repeat some code. Trying to re-use `.table__striped()` seems like the wrong way.

Would the preferred path be to add the explicit striping LESS as `.table-wrapper__scrolling > table`?

**Comment by jimmynotjim** [comment]
What if `.striped-table()` was a base mixin, and it was used within a max-width for `.table__striped-above-xs` and everywhere in `.table__scrolling`? You scope the rules of striping, but use them only where necessary.

**Comment by mistergone** [comment]
Err, yeah, what @jimmynotjim said. My brain wasn't doing LESS well. :sweat_smile: 

I'm going to do just that, then I plan to do another PR (much smaller than the last) for cf-tables.

**Comment by KimberlyMunoz** [comment]
@mistergone is this issue resolved?

**Comment by mistergone** [comment]
Fixed in #12, but not yet merged.

**Comment by mistergone** [comment]
Merged in PR #12!
