### ISSUE TITLE
Reduce nesting on striped styling

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-tables#8]
https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L360-L361

If nothing else is going to go inside `.table__striped`, let's un-nest the `tbody > tr:nth-child(even)`, so we just have `.table__striped tbody > tr:nth-child(even)`.

(Also, can probably use the child selector between `.table__striped` and `tbody`, right?)

**Comment by mistergone** [comment]
Merged in PR #12!
