### ISSUE TITLE
Small whitespace issues

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-tables#9]
- Please add a blank line between each selector in [this chunk](https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L395-L443)
- [L420](https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L420) needs two more spaces of indentation.
- [These two lines](https://github.com/cfpb/cf-tables/blob/gh-pages/src/cf-tables.less#L445-L446) can be removed.

**Comment by KimberlyMunoz** [comment]
@mistergone is this issue resolved?

**Comment by mistergone** [comment]
Fixed in #12, but not yet merged.
